version: '3'

services:
  
  paracasa:
    image: paracasa
    ports: 
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/aplicacionmenu
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    
    build:
      context: "./"
      dockerfile: "Dockerfile"